### ISSUE TITLE
Cannot use component in WinForm application

### ISSUE THREAD

**Issue by fangot14** [glyphard/expo-server-sdk-dotnet#8]
Hello.
I do not understand why the component cannot be installed in my application:
![Installation error](https://user-images.githubusercontent.com/84096090/118022239-6d79e400-b35c-11eb-8b56-7a9460a47f46.jpg)

My project is a WinForm application (Application Windows Forms) using .NetFramework 4.5 but the problem also exists with version 4.6 or other.
I use Visual Studio 2015.
Thank you for any help.

**Comment by glyphard** [comment]
@fangot14 Interesting.  My guess is that because this lib was written for .netcore, this issue is as simple as the lib is not targeting .net standard or not targeting a version of .net framework.  The top answer to this similar stackoverflow question is likely the solution: https://stackoverflow.com/questions/33810504/reference-a-net-core-library-in-a-net-4-6-project

Would you like to make the change and submit a PR?

**Comment by fangot14** [comment]
You are right.
The package can be installed in a .NetCore project.
I do not know this new this new concept but I will go on with it.
Many thanks.
